spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:8081/postgres
    username: postgres
    password: thepassword
    hikari:
      max-lifetime: 1200000
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 50
        hbm2ddl:
          schema_filter_provider: mycode.JpaFilterProvider
    database-platform: mycode.AxonPostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
